import { EBusinessId, EChannelId } from './constants';
import { tmpI18n as i18n } from './i18n';

export interface IChannelItemRaw {
  /** 渠道Id */
  channelId: EChannelId;
  /** 业务Id */
  busiId: EBusinessId;
  /** 用在记录详情页“缴费项目”，用在记录列表页， */
  name: string;
  isShowSteps?: boolean;
  /** 首页卡片底图 */
  accLogo?: string;
  /** 合作商的logo，用在账单页和电子账单页 */
  companyLogo?: string;
  /** 合作商logo，尺寸跟companyLogo有差异 */
  companyLogo2?: string;
  /** 部分商户不想用图片，改用文案 */
  companyLogoWord?: string;
  /** logo跟‘官方合作渠道’竖向排版 */
  isLogoLongitudinal?: boolean;
  /** 添加账号填写指引图 */
  imgNameGuide?: string;
  /** 开通缴费通知提示图 */
  imgNotifyGuide_zh_cn?: string;
  imgNotifyGuide_zh_hk?: string;
  imgNotifyGuide_en?: string;
  /** 公司简称，用在账单页“本期账单已支付xxxx处理中” */
  companyNameShort?: string;
  /** 公司全称，用在：首页卡片，添加页legend，结果页公司信息，电子账单页公司信息 */
  companyNameFull?: string;
  /** 是否隐藏用户姓名的展示，用在记录列表/记录详情/结果页 */
  isHideName: boolean;
  /** 添加账号时的账号最小长度 */
  accountMinLen?: number;
  /** 添加账号时的账号最大长度 */
  accountMaxLen?: number;
  /** 账号字段Label */
  accountNoLabel?: string;
  /** 账号输入输入input类型，默认tel */
  accountNoInputType?: string;
}
type ICChannel = {
  [key in EChannelId]: IChannelItemRaw;
};

export const CHANNEL_LIST: any = {
  [EChannelId.kaiShing]: {
    channelId: EChannelId.kaiShing,
    busiId: EBusinessId.property,
    name: i18n('启胜-物业费', 'zh-cn'),
    name1: i18n('启胜-物业费', 'zh-hk'),
    name2: i18n('启胜-物业费', 'en'),
    isShowSteps: true,
    accLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220527124649/qisheng/kai-shing-acc-bg.png',
    companyLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220706142555/qisheng/kai-shing-logo.png',
    companyLogo2: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220706142555/qisheng/kai-shing-logo.png',
    isLogoLongitudinal: true,
    imgNameGuide: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220527124649/qisheng/kai-shing-imgNameGuide.png',
    imgNotifyGuide_zh_cn:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_cn.png',
    imgNotifyGuide_zh_hk:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_hk.png',
    imgNotifyGuide_en:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_en.png',
    companyNameShort: i18n('启胜-简称'),
    companyNameFull: i18n('启胜管理服务有限公司'),
    isHideName: false,
    accountMinLen: 7,
    accountMaxLen: 12,
    accountNoLabel: i18n('物业编号'),
    accountNoInputType: 'text',
  },
  [EChannelId.supreme]: {
    channelId: EChannelId.supreme,
    busiId: EBusinessId.property,
    name: i18n('超卓-物业费', 'zh-cn'),
    name1: i18n('超卓-物业费', 'zh-hk'),
    name2: i18n('超卓-物业费', 'en'),
    isShowSteps: true,
    accLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220527124649/qisheng/supreme-acc-bg.png',
    companyLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220706142555/qisheng/supreme-logo.png',
    companyLogo2: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220706142555/qisheng/supreme-logo.png',
    isLogoLongitudinal: true,
    imgNameGuide: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220527124649/qisheng/supreme-imgNameGuide.png',
    imgNotifyGuide_zh_cn:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_cn.png',
    imgNotifyGuide_zh_hk:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_hk.png',
    imgNotifyGuide_en:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_en.png',
    companyNameShort: i18n('超卓-简称'),
    companyNameFull: i18n('超卓管理服务有限公司'),
    isHideName: false,
    accountMinLen: 7,
    accountMaxLen: 12,
    accountNoLabel: i18n('物业编号'),
    accountNoInputType: 'text',
  },
  [EChannelId.chiFuFaYuen]: {
    channelId: EChannelId.chiFuFaYuen,
    busiId: EBusinessId.property,
    name: i18n('置富花园-物业费', 'zh-cn'),
    name1: i18n('置富花园-物业费', 'zh-hk'),
    name2: i18n('置富花园-物业费', 'en'),
    isShowSteps: true,
    accLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220527124649/qisheng/chi-fu-fa-yuen-acc-bg.png',
    companyLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220706142555/qisheng/chi-fu-fa-yuan-logo.png',
    companyLogo2: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220706142555/qisheng/chi-fu-fa-yuan-logo.png',
    isLogoLongitudinal: true,
    imgNameGuide: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220527124649/qisheng/chi-fu-fa-yuen-imgNameGuide.png',
    imgNotifyGuide_zh_cn:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_cn.png',
    imgNotifyGuide_zh_hk:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_hk.png',
    imgNotifyGuide_en:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_en.png',
    companyNameShort: i18n('置富花园-简称'),
    companyNameFull: i18n('置富花园有限公司'),
    isHideName: false,
    accountMinLen: 7,
    accountMaxLen: 12,
    accountNoLabel: i18n('物业编号'),
    accountNoInputType: 'text',
  },
  [EChannelId.hongLokYuen]: {
    channelId: EChannelId.hongLokYuen,
    busiId: EBusinessId.property,
    name: i18n('康乐园-物业费', 'zh-cn'),
    name1: i18n('康乐园-物业费', 'zh-hk'),
    name2: i18n('康乐园-物业费', 'en'),
    isShowSteps: true,
    accLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220527124649/qisheng/hong-lok-yuen-acc-bg.png',
    companyLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220706142555/qisheng/hong-lok-yuen-logo.png',
    companyLogo2: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220706142555/qisheng/hong-lok-yuen-logo.png',
    isLogoLongitudinal: true,
    imgNameGuide: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220527124649/qisheng/hong-lok-yuen-imgNameGuide.png',
    imgNotifyGuide_zh_cn:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_cn.png',
    imgNotifyGuide_zh_hk:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_hk.png',
    imgNotifyGuide_en:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_en.png',
    companyNameShort: i18n('康乐园-简称'),
    companyNameFull: i18n('康乐园物业管理有限公司'),
    isHideName: false,
    accountMinLen: 7,
    accountMaxLen: 12,
    accountNoLabel: i18n('物业编号'),
    accountNoInputType: 'text',
  },
  [EChannelId.JLL]: {
    channelId: EChannelId.JLL,
    busiId: EBusinessId.property,
    name: i18n('仲量-物业费', 'zh-cn'),
    name1: i18n('仲量-物业费', 'zh-hk'),
    name2: i18n('仲量-物业费', 'en'),
    isShowSteps: true,
    accLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220420101654/account-bg/JLL.png',
    companyLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220407111104/JLL-logo.png',
    companyLogo2: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220407111104/JLL-logo.png',
    companyLogoWord: i18n('仲量聯行物業管理有限公司'),
    isLogoLongitudinal: true,
    imgNameGuide: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220407105539/imgNameGuide-JLL.png',
    imgNotifyGuide_zh_cn:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_cn.png',
    imgNotifyGuide_zh_hk:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_hk.png',
    imgNotifyGuide_en:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_en.png',
    companyNameShort: i18n('仲量-简称'),
    companyNameFull: i18n('仲量聯行物業管理有限公司'),
    isHideName: false,
    accountNoLabel: i18n('电子账单号码'),
  },
  [EChannelId.residential]: {
    channelId: EChannelId.residential,
    busiId: EBusinessId.property,
    name: i18n('惠信-物业费', 'zh-cn'),
    name1: i18n('惠信-物业费', 'zh-hk'),
    name2: i18n('惠信-物业费', 'en'),
    isShowSteps: true,
    accLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220420101654/account-bg/JLL.png',
    companyLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220407111104/residential-logo.png',
    companyLogo2: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220407111104/residential-logo.png',
    companyLogoWord: i18n('惠信物業管理有限公司'),
    isLogoLongitudinal: true,
    imgNameGuide: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220407105539/imgNameGuide-JLL.png',
    imgNotifyGuide_zh_cn:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_cn.png',
    imgNotifyGuide_zh_hk:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_hk.png',
    imgNotifyGuide_en:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_en.png',
    companyNameShort: i18n('惠信-简称'),
    companyNameFull: i18n('惠信物業管理有限公司'),
    isHideName: false,
    accountNoLabel: i18n('电子账单号码'),
  },
  [EChannelId.horizon]: {
    channelId: EChannelId.horizon,
    busiId: EBusinessId.property,
    name: i18n('海日湾-物业费', 'zh-cn'),
    name1: i18n('海日湾-物业费', 'zh-hk'),
    name2: i18n('海日湾-物业费', 'en'),
    isShowSteps: true,
    accLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220420101654/account-bg/JLL.png',
    companyLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220407111104/horizon-logo.png',
    companyLogo2: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220407111104/horizon-logo.png',
    companyLogoWord: i18n('海日灣物業服務有限公司'),
    isLogoLongitudinal: true,
    imgNameGuide: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220407105539/imgNameGuide-JLL.png',
    imgNotifyGuide_zh_cn:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_cn.png',
    imgNotifyGuide_zh_hk:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_hk.png',
    imgNotifyGuide_en:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_en.png',
    companyNameShort: i18n('海日湾-简称'),
    companyNameFull: i18n('海日灣物業服務有限公司'),
    isHideName: false,
    accountNoLabel: i18n('电子账单号码'),
  },
  [EChannelId.grandeur]: {
    channelId: EChannelId.grandeur,
    busiId: EBusinessId.property,
    name: i18n('君御-物业费', 'zh-cn'),
    name1: i18n('君御-物业费', 'zh-hk'),
    name2: i18n('君御-物业费', 'en'),
    isShowSteps: true,
    accLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220421150953/account-bg/grandeur.png',
    companyLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220126154317/grandeur-logo.png',
    companyLogo2: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220126154317/grandeur-logo.png',
    isLogoLongitudinal: true,
    imgNameGuide:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211201185334/imgNameGuide-grandeur.png',
    imgNotifyGuide_zh_cn:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_cn.png',
    imgNotifyGuide_zh_hk:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_hk.png',
    imgNotifyGuide_en:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_en.png',
    companyNameShort: i18n('君御-简称'),
    companyNameFull: i18n('君御物业管理有限公司'),
    isHideName: false,
    accountNoLabel: i18n('电子账单号码'),
  },
  [EChannelId.maison]: {
    channelId: EChannelId.maison,
    busiId: EBusinessId.property,
    name: i18n('天瑞-物业费', 'zh-cn'),
    name1: i18n('天瑞-物业费', 'zh-hk'),
    name2: i18n('天瑞-物业费', 'en'),
    isShowSteps: true,
    accLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220421150953/account-bg/maison.png',
    companyLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220126154317/maison-logo.png',
    companyLogo2: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220126154317/maison-logo.png',
    isLogoLongitudinal: true,
    imgNameGuide:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211201185409/imgNameGuide-maison.png',
    imgNotifyGuide_zh_cn:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_cn.png',
    imgNotifyGuide_zh_hk:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_hk.png',
    imgNotifyGuide_en:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_en.png',
    companyNameShort: i18n('天瑞-简称'),
    companyNameFull: i18n('天瑞礼宾服务有限公司'),
    isHideName: false,
    accountNoLabel: i18n('电子账单号码'),
  },
  [EChannelId.royalElite]: {
    channelId: EChannelId.royalElite,
    busiId: EBusinessId.property,
    name: i18n('帝誉-物业费', 'zh-cn'),
    name1: i18n('帝誉-物业费', 'zh-hk'),
    name2: i18n('帝誉-物业费', 'en'),
    isShowSteps: true,
    accLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220420101654/account-bg/royal-elite.png',
    companyLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220126154317/royalElite-logo.png',
    companyLogo2: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220126154317/royalElite-logo.png',
    isLogoLongitudinal: true,
    imgNameGuide:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20210906121147/imgNameGuide-royalElite.png',
    imgNotifyGuide_zh_cn:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_cn.png',
    imgNotifyGuide_zh_hk:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_hk.png',
    imgNotifyGuide_en:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_en.png',
    companyNameShort: i18n('帝誉-简称'),
    companyNameFull: i18n('帝誉服务有限公司'),
    isHideName: false,
    accountNoLabel: i18n('电子账单号码'),
  },
  [EChannelId.hongYip]: {
    channelId: EChannelId.hongYip,
    busiId: EBusinessId.property,
    name: i18n('康业-物业费', 'zh-cn'),
    name1: i18n('康业-物业费', 'zh-hk'),
    name2: i18n('康业-物业费', 'en'),
    isShowSteps: true,
    accLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220420101654/account-bg/hongyip.png',
    companyLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220126154317/hongyip-logo.png',
    companyLogo2: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220126154317/hongyip-logo.png',
    isLogoLongitudinal: true,
    imgNameGuide:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20210906121147/imgNameGuide-hongyip.png',
    imgNotifyGuide_zh_cn:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_cn.png',
    imgNotifyGuide_zh_hk:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_zh_hk.png',
    imgNotifyGuide_en:
      'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20211202105413/imgNotify_property_en.png',
    companyNameShort: i18n('康业-简称'),
    companyNameFull: i18n('康业服务有限公司'),
    isHideName: false,
    accountNoLabel: i18n('电子账单号码'),
  },
  [EChannelId.clp]: {
    channelId: EChannelId.clp,
    busiId: EBusinessId.power,
    name: i18n('中华电力-电费', 'zh-cn'),
    name1: i18n('中华电力-电费', 'zh-hk'),
    name2: i18n('中华电力-电费', 'en'),
    isShowSteps: true,
    accLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220420101654/account-bg/clp.png',
    companyLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20210726144951/clp-bill.png',
    companyLogo2: 'https://st.moneydata.hk//res/weixin/hkwallet/v3/utilities/img/logo/companyLogo1_clp.svg',
    imgNameGuide: 'https://st.moneydata.hk//res/weixin/hkwallet/v3/utilities/img/guide/imgNameGuide.svg',
    imgNotifyGuide_zh_cn:
      'https://st.moneydata.hk//res/weixin/hkwallet/v3/utilities/img/guide/imgNotifyGuide_clp_zh_cn.svg',
    imgNotifyGuide_zh_hk:
      'https://st.moneydata.hk//res/weixin/hkwallet/v3/utilities/img/guide/imgNotifyGuide_clp_zh_hk.svg',
    imgNotifyGuide_en: 'https://st.moneydata.hk//res/weixin/hkwallet/v3/utilities/img/guide/imgNotifyGuide_clp_en.svg',
    companyNameShort: i18n('中电-简称'),
    companyNameFull: i18n('中华电力'),
    isHideName: false,
    accountNoLabel: i18n('账户号码'),
  },
  [EChannelId.towngas]: {
    channelId: EChannelId.towngas,
    busiId: EBusinessId.gas,
    name: i18n('Towngas-煤气费', 'zh-cn'),
    name1: i18n('Towngas-煤气费', 'zh-hk'),
    name2: i18n('Towngas-煤气费', 'en'),
    isShowSteps: true,
    accLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20220420101654/account-bg/towngas.png',
    companyLogo: 'https://st.moneydata.hk/res/uploadcdn-static/hkwallet/utilities/20210726144951/towngas-bill.png',
    companyLogo2: 'https://st.moneydata.hk/res/weixin/hkwallet/v3/utilities/img/logo/company_towngas2.png',
    imgNameGuide: 'https://st.moneydata.hk/res/weixin/hkwallet/v3/utilities/img/guide/imgNameGuide_towngas.png',
    imgNotifyGuide_zh_cn:
      'https://st.moneydata.hk/res/weixin/hkwallet/v3/utilities/img/guide/imgNotifyGuide_towngas_zh_cn2.png',
    imgNotifyGuide_zh_hk:
      'https://st.moneydata.hk/res/weixin/hkwallet/v3/utilities/img/guide/imgNotifyGuide_towngas_zh_hk2.png',
    imgNotifyGuide_en:
      'https://st.moneydata.hk/res/weixin/hkwallet/v3/utilities/img/guide/imgNotifyGuide_towngas_en2.png',
    companyNameShort: i18n('Towngas-简称'),
    companyNameFull: i18n('香港中华煤气有限公司'),
    isHideName: true,
    accountNoLabel: i18n('账户号码'),
  },
  [EChannelId.water]: {
    channelId: EChannelId.water,
    busiId: EBusinessId.water,
    name: i18n('水务署-水费', 'zh-cn'),
    name1: i18n('水务署-水费', 'zh-hk'),
    name2: i18n('水务署-水费', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.land]: {
    channelId: EChannelId.land,
    busiId: EBusinessId.land,
    name: i18n('差饷物业估价署-差饷地租', 'zh-cn'),
    name1: i18n('差饷物业估价署-差饷地租', 'zh-hk'),
    name2: i18n('差饷物业估价署-差饷地租', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.judgmentDebt]: {
    channelId: EChannelId.judgmentDebt,
    busiId: EBusinessId.taxes,
    name: i18n('税务局-判定债项利息', 'zh-cn'),
    name1: i18n('税务局-判定债项利息', 'zh-hk'),
    name2: i18n('税务局-判定债项利息', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.property]: {
    channelId: EChannelId.property,
    busiId: EBusinessId.taxes,
    name: i18n('税务局-物业税', 'zh-cn'),
    name1: i18n('税务局-物业税', 'zh-hk'),
    name2: i18n('税务局-物业税', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.taxReserveCertificate]: {
    channelId: EChannelId.taxReserveCertificate,
    busiId: EBusinessId.taxes,
    name: i18n('税务局-购买储税券', 'zh-cn'),
    name1: i18n('税务局-购买储税券', 'zh-hk'),
    name2: i18n('税务局-购买储税券', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.courtFee]: {
    channelId: EChannelId.courtFee,
    busiId: EBusinessId.taxes,
    name: i18n('税务局-法院费用', 'zh-cn'),
    name1: i18n('税务局-法院费用', 'zh-hk'),
    name2: i18n('税务局-法院费用', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.stamp]: {
    channelId: EChannelId.stamp,
    busiId: EBusinessId.taxes,
    name: i18n('税务局-印花税', 'zh-cn'),
    name1: i18n('税务局-印花税', 'zh-hk'),
    name2: i18n('税务局-印花税', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.branchRegistrationFee]: {
    channelId: EChannelId.branchRegistrationFee,
    busiId: EBusinessId.taxes,
    name: i18n('税务局-分行登记费', 'zh-cn'),
    name1: i18n('税务局-分行登记费', 'zh-hk'),
    name2: i18n('税务局-分行登记费', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.businessRegistrationFee]: {
    channelId: EChannelId.businessRegistrationFee,
    busiId: EBusinessId.taxes,
    name: i18n('税务局-商业登记费', 'zh-cn'),
    name1: i18n('税务局-商业登记费', 'zh-hk'),
    name2: i18n('税务局-商业登记费', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.personalAssessment]: {
    channelId: EChannelId.personalAssessment,
    busiId: EBusinessId.taxes,
    name: i18n('税务局-个人入息课税', 'zh-cn'),
    name1: i18n('税务局-个人入息课税', 'zh-hk'),
    name2: i18n('税务局-个人入息课税', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.salaries]: {
    channelId: EChannelId.salaries,
    busiId: EBusinessId.taxes,
    name: i18n('税务局-薪俸税', 'zh-cn'),
    name1: i18n('税务局-薪俸税', 'zh-hk'),
    name2: i18n('税务局-薪俸税', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.profit]: {
    channelId: EChannelId.profit,
    busiId: EBusinessId.taxes,
    name: i18n('税务局-利得税', 'zh-cn'),
    name1: i18n('税务局-利得税', 'zh-hk'),
    name2: i18n('税务局-利得税', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.paymentSlip]: {
    channelId: EChannelId.paymentSlip,
    busiId: EBusinessId.general,
    name: i18n('政府一般缴款单', 'zh-cn'),
    name1: i18n('政府一般缴款单', 'zh-hk'),
    name2: i18n('政府一般缴款单', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.companyRegistered]: {
    channelId: EChannelId.companyRegistered,
    busiId: EBusinessId.general,
    name: i18n('公司注册处', 'zh-cn'),
    name1: i18n('公司注册处', 'zh-hk'),
    name2: i18n('公司注册处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.officialReceiver]: {
    channelId: EChannelId.officialReceiver,
    busiId: EBusinessId.general,
    name: i18n('破产管理署', 'zh-cn'),
    name1: i18n('破产管理署', 'zh-hk'),
    name2: i18n('破产管理署', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.transport1]: {
    channelId: EChannelId.transport1,
    busiId: EBusinessId.general,
    name: i18n('运输署', 'zh-cn'),
    name1: i18n('运输署', 'zh-hk'),
    name2: i18n('运输署', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.transport2]: {
    channelId: EChannelId.transport2,
    busiId: EBusinessId.general,
    name: i18n('运输署', 'zh-cn'),
    name1: i18n('运输署', 'zh-hk'),
    name2: i18n('运输署', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.transport3]: {
    channelId: EChannelId.transport3,
    busiId: EBusinessId.general,
    name: i18n('运输署', 'zh-cn'),
    name1: i18n('运输署', 'zh-hk'),
    name2: i18n('运输署', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.transport4]: {
    channelId: EChannelId.transport4,
    busiId: EBusinessId.general,
    name: i18n('运输署', 'zh-cn'),
    name1: i18n('运输署', 'zh-hk'),
    name2: i18n('运输署', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.transport5]: {
    channelId: EChannelId.transport5,
    busiId: EBusinessId.general,
    name: i18n('运输署', 'zh-cn'),
    name1: i18n('运输署', 'zh-hk'),
    name2: i18n('运输署', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration1]: {
    channelId: EChannelId.immigration1,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration2]: {
    channelId: EChannelId.immigration2,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration3]: {
    channelId: EChannelId.immigration3,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration4]: {
    channelId: EChannelId.immigration4,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration5]: {
    channelId: EChannelId.immigration5,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration6]: {
    channelId: EChannelId.immigration6,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration7]: {
    channelId: EChannelId.immigration7,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration8]: {
    channelId: EChannelId.immigration8,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration9]: {
    channelId: EChannelId.immigration9,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration10]: {
    channelId: EChannelId.immigration10,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration11]: {
    channelId: EChannelId.immigration11,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration12]: {
    channelId: EChannelId.immigration12,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration13]: {
    channelId: EChannelId.immigration13,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration14]: {
    channelId: EChannelId.immigration14,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration15]: {
    channelId: EChannelId.immigration15,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration16]: {
    channelId: EChannelId.immigration16,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration17]: {
    channelId: EChannelId.immigration17,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration18]: {
    channelId: EChannelId.immigration18,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration19]: {
    channelId: EChannelId.immigration19,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration20]: {
    channelId: EChannelId.immigration20,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration21]: {
    channelId: EChannelId.immigration21,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration22]: {
    channelId: EChannelId.immigration22,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration23]: {
    channelId: EChannelId.immigration23,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration24]: {
    channelId: EChannelId.immigration24,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration25]: {
    channelId: EChannelId.immigration25,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration26]: {
    channelId: EChannelId.immigration26,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration27]: {
    channelId: EChannelId.immigration27,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration28]: {
    channelId: EChannelId.immigration28,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration29]: {
    channelId: EChannelId.immigration29,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration30]: {
    channelId: EChannelId.immigration30,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration31]: {
    channelId: EChannelId.immigration31,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.immigration32]: {
    channelId: EChannelId.immigration32,
    busiId: EBusinessId.general,
    name: i18n('入境事务处', 'zh-cn'),
    name1: i18n('入境事务处', 'zh-hk'),
    name2: i18n('入境事务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.civilAidService]: {
    channelId: EChannelId.civilAidService,
    busiId: EBusinessId.general,
    name: i18n('民众安全服务处', 'zh-cn'),
    name1: i18n('民众安全服务处', 'zh-hk'),
    name2: i18n('民众安全服务处', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.homeAffairs]: {
    channelId: EChannelId.homeAffairs,
    busiId: EBusinessId.general,
    name: i18n('民政事务总署（牌照事务处）', 'zh-cn'),
    name1: i18n('民政事务总署（牌照事务处）', 'zh-hk'),
    name2: i18n('民政事务总署（牌照事务处）', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.health]: {
    channelId: EChannelId.health,
    busiId: EBusinessId.general,
    name: i18n('卫生署', 'zh-cn'),
    name1: i18n('卫生署', 'zh-hk'),
    name2: i18n('卫生署', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
  [EChannelId.communicationsAuthority]: {
    channelId: EChannelId.communicationsAuthority,
    busiId: EBusinessId.general,
    name: i18n('通讯事务管理局办公室', 'zh-cn'),
    name1: i18n('通讯事务管理局办公室', 'zh-hk'),
    name2: i18n('通讯事务管理局办公室', 'en'),
    isShowSteps: false,
    isHideName: false,
  },
};
